### ISSUE TITLE
As a speaker, I should be able to RSVP for VIP reception and happy hour on portal—this should be added to Speaker Response Form.

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/Conference-for-Good#11]

**Comment by jasonsreynolds** [comment]
"Speaker Meals" to "Speaker Meals and Events" with two additional check boxes. Brooke to provide details.

**Comment by bonham000** [comment]
Some information:

In order for a speaker to have access to the speaker response form they must 1) create an account 2) propose a talk 3) have the talk approved by admin and 4) have the talk scheduled by an admin (which requires the admin to add date + time + room for talk scheduling).

**Comment by bonham000** [comment]
This has been added.
