### ISSUE TITLE
Continuing problem with Mailgun & password reset feature

### ISSUE THREAD

**Issue by bonham000** [freeCodeCamp/Conference-for-Good#40]
In lieu of solving/fixing this, what workaround can we create?

We could potentially send a duplicate email to Brooke whenever a user resets their password so she should also receive the email. If the user somehow does not, then Brooke should also have it to notify them.

**Comment by amashamdan** [comment]
I think this is a good idea and easy to implement!

**Comment by bonham000** [comment]
I implemented this feature and will close this for now.
