### ISSUE TITLE
Delete Speakers and Workshops Feature

### ISSUE THREAD

**Issue by bonham000** [freeCodeCamp/Conference-for-Good#55]
- Need ability to delete speakers and workshops.
- Need to be able to delete both individual and bulk uploads to speakers.

**Comment by bonham000** [comment]
So admin uploads a document to an individual speaker, admin should be able to delete that document.

**Comment by bonham000** [comment]
As a speaker, in uploads > upload handouts, the speaker should be able to delete uploaded handouts.

**Comment by yzhbankov** [comment]
I can take this issue if nobody work on it. But i need some additional info. As for speakers and workshops it is clear for me but i don't understand about uploads. What do you mean? Or maybe second part is just about individual and bulk remove of speakers and workshops?

**Comment by bonham000** [comment]
Hi @yzhbankov 

Because this project is currently an in-process non-profit project, we are trying to maintain all the issues directly with the team assigned to this. This project is a little odd because it is a legacy app and has been moved into the freeCodeCamp repository so is essentially public, however, it is also currently in production so the issues are higher priority for the stakeholder. Also, to effectively work on this it requires various sensitive login details from the stakeholder, so we are trying to keep this within the current team at the moment. Once this current project is completed and this app fully becomes an Open Source for Good project it should become more open to outside contributions.

Thanks a lot for your interest in helping out!
