### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by yzhbankov** [freeCodeCamp/Conference-for-Good#59]
Hi, everybody.
I started this app locally and finded some things:
- in registration form it is not clear that password should be longer then 5 symbols;
- why after signing up the user should make sign in;
- in "Create proposal" menu when i click btn Submit nothing is happens;
- when i try to upload image in Upload Headshot menu appears the error. In console "Failed to load resource";
- when i refreshing the page my session is losting and i must re sign in.

If this is a bugs i can work on them or maybe there are some other tasks that needs in volunteers work.

**Comment by bonham000** [comment]
Thanks for this issue! We are currently working on this project. In order for it to run locally properly, a little setup is required beforehand. You have to have a local database running, for instance. That would account for most of the errors you are seeing.

**Comment by yzhbankov** [comment]
Do you mean mongoDB?
I run it locally.

**Comment by bonham000** [comment]
@yzhbankov yes, you need to have mongoDB running and you have to seed it with initial information using one of the `database-seed` branches you can find here in the code repository. This is not totally clear at the moment but like I mentioned this is currently being worked on as an FCC non-profit project. So the entire thing is in-progress and we are aiming to make a lot of updates. Adding better instructions for the initial project setup, development environment, etc. will be good to do.

**Comment by yzhbankov** [comment]
I setup project locally from database-seed-branch.
When i go to 'Create proposal' menu in my console the following error is appeared:

Error: Uncaught (in promise): TypeError: Cannot read property 'title' of undefined
    at resolvePromise (vendor.bundle.js:126930)
    at vendor.bundle.js:126907
    at ZoneDelegate.invoke (vendor.bundle.js:126704)
    at Object.onInvoke (vendor.bundle.js:51075)
    at ZoneDelegate.invoke (vendor.bundle.js:126703)
    at Zone.run (vendor.bundle.js:126597)
    at vendor.bundle.js:126963
    at ZoneDelegate.invokeTask (vendor.bundle.js:126737)
    at Object.onInvokeTask (vendor.bundle.js:51066)
    at ZoneDelegate.invokeTask (vendor.bundle.js:126736)

And i cant submit proposal. Do you have such an error?

**Comment by bonham000** [comment]
Are you on master? The seed branch is out of date.

**Comment by yzhbankov** [comment]
I update my local repo and when i working from master the server crushes in the moment i try to login.
When i working from database-seed-branch I cant save proposal and in console appears following error:
Error: Uncaught (in promise): TypeError: Cannot read property 'title' of undefined.
From what branch do you working?

**Comment by amashamdan** [comment]
To be able to save a proposal, you need to setup a conference first. You need to login as an admin and crate a conference first.

**Comment by yzhbankov** [comment]
Unfortunately i can't found how to login as an admin.

**Comment by amashamdan** [comment]
After you create an account, you can update your information in the local database and set "admin" property to true.
