### ISSUE TITLE
As an admin, I should not see archived presenters in the drop down when assigning speakers to a session.

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/Conference-for-Good#7]

**Comment by bonham000** [comment]
What is the purpose of archiving speakers?

**Comment by amashamdan** [comment]
Not really sure. But I added this feature (still testing it locally).

**Comment by bonham000** [comment]
If you figured this out — awesome! I tried to work on this last night and made no progress! Stuck in Angular 2...
