### ISSUE TITLE
As a user, the dashboard should show a greeting, the scheduled presentation link should work, co-presenters and presentation dates should be displayed, and required actions (or "None") should be displayed.

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/Conference-for-Good#8]

**Comment by jasonsreynolds** [comment]
Brooke will provide a screenshot for us of a working and broken dashboard page.

**Comment by bonham000** [comment]
"My Scheduled Presentations" should show copresenters and scheduled for.

"Speaking Terms" should also be populated.

'Schedule and action required' are necessary for speakers to see.

**Comment by amashamdan** [comment]
If no action is required, "None" should be seen in the "Action Required" section. The glitchy page (from the screenshot) doesn't show anything in that section. (probably the actions required are not showing and not the word "None").

**Comment by bonham000** [comment]
This is tentatively fixed now — hopefully, any further bugs (if we see them) can be dealt with using the Angular Safe Navigation Operator on other fields that are producing async problems.
